### ISSUE TITLE
The granularity of action autoregression when evaluated on RLBench

### ISSUE THREAD

**Issue by chenyt31** [mlzxy/arp#12]
Thank you for your excellent work!

I have some questions regarding the design aspect of your approach. I noticed that the model's input consists of the current observation, and during the forward pass, it autoregressively outputs each component of the action (including coarse-grained position, fine-grained position, three rotation angles, gripper action, and collision). In other words, the granularity of the autoregression is at single action level. However, during task completion, the previous action is not used as a prompt sequence for predicting the next action (task level). Existing works such as VIMA, Gato, and GR1 seem to follow the latter approach (task level)?

Is my understanding correct? If I understand correctly, why not treat the previous actions as part of the prompt sequence?

Do you have any insights on this aspect?

Thank you!

**Comment by mlzxy** [comment]
I think your understanding is roughly correct. I don't use previous action sequences as prompts. But from what I know, VIMA and GR1 also don't generate from previous actions. I could be wrong here. 

Regarding why, the short answer is I just didn't test it. The long answer is that, I believe previous actions are useful in some but not all cases. I will give you some examples: 

1. Useful case: In tasks that require sequential reasoning like [language table](https://github.com/google-research/language-table), previous actions will be beneficial. For example, the common pattern of pushing in a certain direction will be much easier to learn when previous actions are present. There could be more examples.

2. Not-so-useful case (maybe): In manipulation tasks, especially if the task length is short, I believe the benefits of previous actions will be small. Because actions in these tasks highly depend on where the objects are, how the objects look like. Since all previous actions are already executed, their effects are already present in the visual observation. 

----

Essentially, we can understand this from a Markovian perspective.  I believe if the tasks require the demonstrator to act non-markovianly, then previous data are more useful.

**Comment by chenyt31** [comment]
Thank you for your insightful and inspiring insights!
