### ISSUE TITLE
Demonstrations used in eval

### ISSUE THREAD

**Issue by rebecajohn** [mlzxy/arp#14]
In Table A4 , how many demonstrations were used for eval ? if its 70 why 70 ? why not 10 or 100 ?

**Comment by mlzxy** [comment]
Table A4 is the RLBench per-task result. 25 episodes are evaluated for each task, 100 demonstrations per task are used for training.

For the real-robot tasks, I collect 70 demonstrations. The reason is simply because 70 demonstrations may just be enough. More demonstrations take more manual labor to collect, 10 demonstrations may just be too few.
